### ISSUE TITLE
A server doesn't respond to any other hosts than those specified

### ISSUE THREAD

**Issue by davidkregl** [revolunet/gitlab-docker-rancher-letsencrypt-setup#1]
Hello,

how did you setup the server to respond to any other hosts than those, who have containers with their hosts? For example, when I enter the IP address of the server in the browser I would like to be redirected to one of the hosts which I specify. I am getting 503 Service Not Available error instead.

Thank you

**Comment by revolunet** [comment]
i think this setup works better when using DNS, because nginx makes the reverseproxy and redirects you to the right container

**Comment by davidkregl** [comment]
Thanks for the quick reply! Even when I try to enter subdomain.mydomain.com it doesn't redirect me to any container. Let's say I want to redirect all subdomains to a certain container. Can I use wildcards for that?

**Comment by revolunet** [comment]
if you dont need subdomain handling then this setup is overkill, and its designed just for this so you may look at another nginx+docker setup, with a single letsencrypt registration
